### ISSUE TITLE
qual é a licença deste repositório?

### ISSUE THREAD

**Issue by ghost** [DanielNoog/site-arte-brasileira#1]
Oi.

Gostaria de saber qual é a licença deste repositório. Qual é a licença deste repositório? é o MIT? GPL? Unlicensed? (Gostaria de usar o repositório para algo que estou fazendo, criando)

**Comment by DanielNoog** [comment]
> Oi.
> 
> Gostaria de saber qual é a licença deste repositório. Qual é a licença deste repositório? é o MIT? GPL? Unlicensed? (Gostaria de usar o repositório para algo que estou fazendo, criando)

Opa, beleza? Deixei o repositório com licença MIT

**Comment by ghost** [comment]
Oi DanielNoog.

> Opa, beleza? Deixei o repositório com liçença MIT

show ^^, valeu mano pela informação. ps: a licença MIT é uma grandes licenças, eu gosto bastante.
